### ISSUE TITLE
I can't run this code

### ISSUE THREAD

**Issue by zyzyz000000** [UttaranB127/STEP#1]
There a lot of problems when I run the code. Can you provide information about your experimental environment? Thanks!

**Comment by rohanchandra30** [comment]
Hi,

Could you clarify the exact issues that you are facing?

Thanks!

**Comment by zyzyz000000** [comment]
Hi,

The previous issue may be caused by the environment version, which has now been resolved. Thanks for your reply!

In STEP/classifier_stgcn_real_only/main.py, there is a small issue on line 75. There is no function 'split_data' in 'loader.py'. Its function seems to be merged into  function 'load_data'. Not a big problem, I can modify it myself. 
Anyway thanks for your code!

In addition, I did not find affective features in dataset. Will affective features be made public?

**Comment by UttaranB127** [comment]
Hi, thanks a lot for identifying the issues! We'll address them and push the updated code!

We are also in the process of preparing a proper documentation. Hopefully, things will become much clearer once that is up.

We have python codes for creating the affective features corresponding to the joint information, we'll push that soon as well. Meanwhile, I have uploaded the affective features for the real 2,177 data points in the Google drive (https://go.umd.edu/emotion-gait) with the rest of the dataset. The files are called 'affectiveFeatures.h5' (our 342) and 'affectiveFeatures_ELMD.h5' (1,835 from ELMD). Please let us know if you have any issues using them.

**Comment by UttaranB127** [comment]
Closing this since there has been no further questions
