### ISSUE TITLE
Using a 2D dataset instead of a 3D dataset

### ISSUE THREAD

**Issue by AndreyGalitsin** [UttaranB127/STEP#10]
Dear Uttaran, I want to use a 2D pose dataset instaed of a 3D, that you use in this work. Tell me please what does 'in_channels'  there https://github.com/UttaranB127/STEP/blob/master/classifier_stgcn_real_only/net/classifier.py#L19 mean?

Is it responsible for 3 (RGB) image channels or it is about 3 dimensional input data and if I want to use a 2D dataset, I have to set in_channels=2?

**Comment by UttaranB127** [comment]
Yes, it refers to three-dimensional input data. In order to use 2D input, you can change in_channels to 2, and the input would two-dimensional joint locations (could be either image space or metric space).

**Comment by AndreyGalitsin** [comment]
I understand, thank you so much!
