### ISSUE TITLE
Some questions about the dataset 

### ISSUE THREAD

**Issue by cvychen** [UttaranB127/STEP#11]
Hello sir, I have found that the scale of dataset depicted in the paper is different from the one in the website.
In the paper,  there are 5227 = 4227(real) + 1000(synthetic). However, I get 6177=2177(real) + 4000(stnthetic) in the website. Please tell me the reason.

**Comment by UttaranB127** [comment]
Hello, thanks for your question. We had to make changes to the dataset since its original upload (primarily due to logistical issues and expiring storage permissions) and as a result, there are fewer of the originals currently available. I hope this answers your question.

**Comment by cvychen** [comment]
Thanks so much for your reply! I get it.

**Comment by cvychen** [comment]
Hello Uttaran,
       I want to know whether should I translate the labels [angry,happy,neutral,sad] to be [0,1,2,3] when I use the synthetic dataset. Because when I open the real dataset label file, I have found the rule is not suitable. As following words you see:
/001_Angry_positions.csv:1 /001_Happy_positions.csv:3 /001_Neutral_positions.csv:1 /001_Sad_positions.csv:3;
/002_Angry_positions.csv:1 /002_Happy_positions.csv:3 /002_Neutral_positions.csv:3 /002_Sad_positions.csv:3;
/003_Angry_positions.csv:1 /003_Happy_positions.csv:0 /003_Neutral_positions.csv:3 /003_Sad_positions.csv:2;
I hope to hear your explanation。
Thanks！

**Comment by UttaranB127** [comment]
Thanks for your observation! The labels map one-to-one to the following: [0, 1,2 3] -> ['Angry', 'Neutral', 'Happy', 'Sad']. You can find the mapping in multiple places in our code, e.g., in `classifier_stgcn_real_only/main.py`, line 75.

The file names actually indicate the _intended_ emotions of the subjects whose gaits constitute our dataset. The labels are the _perceived_ emotions that labelers assigned after looking at the gait data. We use the perceived emotions in our experiments.

**Comment by cvychen** [comment]
Thanks for your explanation! Have you run the model on the modified dataset as the dataset is different from the one depicted in your paper? Could you please tell me the accuracy you get and the parameter you set during the training time if you have done it?

**Comment by UttaranB127** [comment]
No sorry, we have not tested this method on other datasets yet.

**Comment by cvychen** [comment]
Thanks for your kind reply!
