### ISSUE TITLE
Excuse me.Some new questions about datasets.

### ISSUE THREAD

**Issue by Mcudll929** [UttaranB127/STEP#13]
Hello Uttaran,i have some questions about the datasets that you posted on GoogleCloud.
i found that the real gaits on GoogleCloud have 112+1048 angry samples、33+454 neutral samples、78+254 happy samples and 119+79 sad samples respectively from 342 were collected by you and the remaining 1,835 were taken from the ELMD.
Firstly,In the paper, there are 4227 real samples. However,the number of neutral/angry samples became less.Is there much difference between the datasets in parper and that of GoogleCloud?
Then,the input gaits were converted to 21-joint skeletons in the paper.but that of github code is 16.
Finally,may i ask when you can upload the latest datasets.
Looking forward to your reply

**Comment by UttaranB127** [comment]
Hello, as mentioned in the other issue threads, there are differences between the dataset in Google cloud and the dataset mentioned in the paper, mainly due to expiring permissions to some parts of the dataset. The uploaded dataset is the latest version that you can use for your purposes.
