### ISSUE TITLE
Questions regarding paper x code compatibility

### ISSUE THREAD

**Issue by maluwastaken** [UttaranB127/STEP#20]
Hi! In the paper you name 3 models, with STEP+Aug being the one with the best accuracy. Is STEP+Aug equivalent with the model on the [classifier_stgcn_real_and_synth](https://github.com/UttaranB127/STEP/tree/master/classifier_stgcn_real_and_synth) folder? Also, in the mainf file for classifier_stgcn_real_and_synth, the synth filename is 'CVAEGCN_best' but I couldn't find it in the provided [dataset](https://drive.google.com/drive/u/1/folders/1g9fv2jwwBZrAl88qbzV8e_X6qKn4TVkh) nor inside the repository. I appreciate your help!

**Comment by UttaranB127** [comment]
Hi, sorry this repo is no longer actively maintained, so some of the contents may be outdated. That said:

"Is STEP+Aug equivalent with the model on the [classifier_stgcn_real_and_synth](https://github.com/UttaranB127/STEP/tree/master/classifier_stgcn_real_and_synth) folder?" - Yes

"couldn't find it in the provided [dataset](https://drive.google.com/drive/u/1/folders/1g9fv2jwwBZrAl88qbzV8e_X6qKn4TVkh) nor inside the repository" - You're right that "best" is not in the dataset. You can use featuresCVAEGCN_1_2000.h5 and featuresCVAEGCN_2001_4000.h5 instead.
